runtime: python39  # Specify your Python version

entrypoint: gunicorn -b :$PORT app:app  # Flask app entry point (adjust if your app structure is different)

env_variables:
  FLASK_ENV: production  # Environment variable for Flask (adjust as needed)

instance_class: F2  # Optional, specify the type of instance (adjust as needed)

handlers:
  - url: /static  # Serve static files
    static_dir: static/

  - url: /.*  # Serve all requests to the Flask app
    script: auto
